# Generated by Django 2.2.8 on 2020-03-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', 'Male'), ('女', 'Female')], max_length=6, verbose_name='性别')),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='单位名称')),
                ('phone', models.CharField(max_length=11, verbose_name='单位联系电话')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Unit', verbose_name='工作单位')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='社团名称')),
                ('club_status', models.CharField(choices=[('dj', '冻结'), ('cx', '撤销'), ('zc', '正常')], max_length=2, verbose_name='社团状态')),
                ('club_category', models.CharField(choices=[('wyty', '文娱体育'), ('whzh', '文化综合'), ('gysj', '公益实践'), ('wlss', '忘了是啥')], max_length=4, verbose_name='社团类别')),
                ('create_time', models.DateField(verbose_name='成立时间')),
                ('particular_year', models.CharField(max_length=4, verbose_name='运行年份')),
                ('description', models.CharField(max_length=50, verbose_name='社团描述')),
                ('purpose', models.CharField(max_length=50, verbose_name='社团宗旨')),
                ('icon', models.ImageField(upload_to='', verbose_name='社团图标')),
                ('affiliatedUnits', models.ManyToManyField(to='management.Unit', verbose_name='挂靠单位')),
                ('guidanceTeacher', models.ManyToManyField(to='management.Teacher', verbose_name='指导老师')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='活动名称')),
                ('description', models.CharField(max_length=200, verbose_name='活动内容')),
                ('date', models.DateTimeField(verbose_name='活动时间')),
                ('activityType', models.CharField(choices=[('大型活动', 'Large-scale'), ('常规活动', 'Regular'), ('素拓活动', 'Extension')], max_length=12, verbose_name='活动类型')),
                ('peopleCount', models.IntegerField(verbose_name='活动参与人数')),
                ('venue', models.CharField(max_length=30, verbose_name='活动地点')),
                ('score', models.IntegerField(verbose_name='活动分数')),
                ('cooperatedClub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooper', to='management.Club', verbose_name='协办社团')),
                ('mainClub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='management.Club', verbose_name='主办社团')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.People')),
                ('affiliated_college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Unit', verbose_name='所属学院')),
            ],
            bases=('management.people',),
        ),
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='president', to='management.Student', verbose_name='会长'),
        ),
        migrations.AddField(
            model_name='club',
            name='vicePresident',
            field=models.ManyToManyField(related_name='vicePresident', to='management.Student', verbose_name='副会长'),
        ),
    ]
