# Generated by Django 2.2.8 on 2020-03-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200306_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='people_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='people_ptr',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('男', 'Male'), ('女', 'Female')], default=12, max_length=6, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=21, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=12, max_length=10, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=12321314, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('男', 'Male'), ('女', 'Female')], default=1, max_length=6, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=1, max_length=10, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
